### ISSUE TITLE
Thank you for your open source, can you provide a UI demo

### ISSUE THREAD

**Issue by xhzengAIB** [rosettastone/RSTCoreDataKit#2]
@jessesquires 
Hi! 

Check after the test case, I'm still a little don't understand, you can provide a Demo is better with the UI.

Jack

**Comment by jessesquires** [comment]
Hey @xhzengAIB - we've added an example project. It's very basic and we will be improving it soon.

**Comment by xhzengAIB** [comment]
Hi! @jessesquires 

Very good, thank you for your enthusiastic.

I learn you a lot of code
