### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by xhzengAIB** [rosettastone/RSTCoreDataKit#3]
Hi! @jessesquires 

If I have 10000000 data need to mark, if it do that?

Jack

**Comment by jessesquires** [comment]
Hey @xhzengAIB !

This library is built on top of Core Data, so the size of your datasets and performance will be constrained by the Core Data framework itself.

**Comment by xhzengAIB** [comment]
Hi! @jessesquires 

Ok! I see, thank you for your answer
