### ISSUE TITLE
UITableView Information

### ISSUE THREAD

**Issue by mrhaxic** [rosettastone/RSTCoreDataKit#7]
hi
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
  {
  UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"cell" forIndexPath:indexPath];
  
  return cell;
  }

in this code how can i get the information of indexPath.row for the core data ?

**Comment by jessesquires** [comment]
hey @mrhaxic - not really sure what you mean. What are you trying to do?

**Comment by mrhaxic** [comment]
@jessesquires I mean to return the first result of the Core Data I saved already if I have 20 rows

**Comment by jessesquires** [comment]
Hey @mrhaxic - this doesn't sound like something specific to `RSTCoreDataKit`. I would recommend asking this on StackOverflow.
